### ISSUE TITLE
EasyRecyclerAdapter listener NullPointerException

### ISSUE THREAD

**Issue by tonilopezmr** [cmc00022/easyrecycleradapters#9]
When the EasyRecyclerViewManagerBuilder doesn't call clickListener or longClickListener and this event  is called, happen this error.

**Comment by tonilopezmr** [comment]
UPSS! I have made a mistake :( I wanted to create a pull request :/

**Comment by tonilopezmr** [comment]
Sorry, but the version 1.0.7 has not changes. 

The 1.0.7 source.jar and 1.0.6 is the same jar.

**Comment by cmc00022** [comment]
Let me have a lot at it I might have done something wrong then. Sorry for the inconvenience

**Comment by cmc00022** [comment]
@tonilopezmr could you try version 1.0.8 and let me know? Thanks.

**Comment by tonilopezmr** [comment]
All right! 1.0.8 works.

**Comment by cmc00022** [comment]
awesome :)
